### ISSUE TITLE
Page does not load if CalendarView's IsVisible property is set.

### ISSUE THREAD

**Issue by oguja** [ME-MarvinE/XCalendarGettingStarted#3]
Hi there,

I seem to be having a problem with the control where if I set the IsVisible property on it , the ContentPage hosting it will not load. I have tried this with a new AppShell tabbed project and a new App Project. With the former the tabour comes up, but the tab of the page that hosts the control does not load. With the latter, the page just doesn't come up at all. 

Both tests use the simple example shown on the getting started page [here](https://github.com/ME-MarvinE/XCalendarGettingStarted) repeated below:

**VM**
`public Calendar<CalendarDay> MyCalendar { get; set; } = new Calendar<CalendarDay>();`

**Xaml**
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="App1.MainPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:xc="clr-namespace:XCalendar.Forms.Views;assembly=XCalendar.Forms">
    
        <xc:CalendarView
            Days="{Binding MyCalendar.Days}"
            DaysOfWeek="{Binding MyCalendar.DayNamesOrder}"
            NavigatedDate="{Binding MyCalendar.NavigatedDate}"/>

</ContentPage>
```
As far as I can see, this issue has not been reported yet, but apologies for any trouble if I have missed it. I have added the AppShell project here and the CalendarView is used on the  ItemsPage.Xaml and its corresponding ItemsViewMode view model.

Any help will be much appreciated.

Kind regards

Test details:
Platform: Xamarin Forms (5.0.0.2662)
Calendar (4.6.0)
[xCalendarTest.zip](https://github.com/ME-MarvinE/XCalendarGettingStarted/files/15287665/xCalendarTest.zip)

**Comment by ME-MarvinE** [comment]
Here's the link to the same issue in the XCalendar repo for future reference:
ME-MarvinE/XCalendar#187
